version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN} # from .env
    volumes:
      - ./vaultwarden_data:/data
    ports:
      - "8080:80"
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - uptime_kuma_data:/app/data
    ports:
      - "3001:3001"
    restart: unless-stopped

volumes:
  vaultwarden_data:
  uptime_kuma_data:
